//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEHO.Baseball.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batter
    {
        public int ID { get; set; }
        public int MLBAM_ID { get; set; }
        public Nullable<int> AtBats { get; set; }
        public Nullable<int> Runs { get; set; }
        public Nullable<int> Hits { get; set; }
        public Nullable<int> RBI { get; set; }
        public Nullable<int> Singles { get; set; }
        public Nullable<int> Doubles { get; set; }
        public Nullable<int> Triples { get; set; }
        public Nullable<int> Homeruns { get; set; }
        public Nullable<int> Walks { get; set; }
        public Nullable<int> Strikeouts { get; set; }
        public Nullable<int> HitByPitch { get; set; }
        public Nullable<int> StolenBases { get; set; }
        public Nullable<int> CaughtStealing { get; set; }
        public Nullable<int> Errors { get; set; }
    }
}
