//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEHO.Baseball.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batter
    {
        public int ID { get; set; }
        public int MLBAM_ID { get; set; }
        public int AtBats { get; set; }
        public int Runs { get; set; }
        public int Hits { get; set; }
        public int RBI { get; set; }
        public int Singles { get; set; }
        public int Doubles { get; set; }
        public int Triples { get; set; }
        public int Homeruns { get; set; }
        public int Walks { get; set; }
        public int Strikeouts { get; set; }
        public int HitByPitch { get; set; }
        public int StolenBases { get; set; }
        public int CaughtStealing { get; set; }
        public int Errors { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
