//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEHO.Baseball.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitcher
    {
        public int ID { get; set; }
        public int MLBAM_ID { get; set; }
        public Nullable<int> Games { get; set; }
        public Nullable<int> GamesStarted { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
        public int Saves { get; set; }
        public double InningsPitched { get; set; }
        public int Hits { get; set; }
        public int HomerunsAllowed { get; set; }
        public int Walks { get; set; }
        public int Strikeouts { get; set; }
        public int HitBatters { get; set; }
        public int Runs { get; set; }
        public int EarnedRuns { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
